baseURL = "https://dennis960.com/Blog/"
languageCode = "en-us"
title = "Blog by Dennis"
theme = "hugo-swift-theme"
RelativeURLs = true
CanonifyURLs = true

[params]
  [params.designer]
    name = "Dennis"

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 2
[minify]
  disableJS = true
